// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240313175051_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            EnclosureId = -6,
                            Name = "lion-2",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            EnclosureId = -6,
                            Name = "lion-3",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -3,
                            EnclosureId = -6,
                            Name = "lion-4",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -4,
                            EnclosureId = -6,
                            Name = "lion-5",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -5,
                            EnclosureId = -6,
                            Name = "lion-6",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -6,
                            EnclosureId = -6,
                            Name = "lion-7",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -7,
                            EnclosureId = -6,
                            Name = "lion-8",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -8,
                            EnclosureId = -6,
                            Name = "lion-9",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -9,
                            EnclosureId = -6,
                            Name = "lion-10",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -10,
                            EnclosureId = -6,
                            Name = "lion-11",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -11,
                            EnclosureId = -6,
                            Name = "giraffe-12",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -12,
                            EnclosureId = -6,
                            Name = "giraffe-13",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -13,
                            EnclosureId = -6,
                            Name = "giraffe-14",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -14,
                            EnclosureId = -6,
                            Name = "giraffe-15",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -15,
                            EnclosureId = -6,
                            Name = "giraffe-16",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -16,
                            EnclosureId = -6,
                            Name = "giraffe-17",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -17,
                            EnclosureId = -6,
                            Name = "giraffe-18",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -18,
                            EnclosureId = -6,
                            Name = "giraffe-19",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -19,
                            EnclosureId = -6,
                            Name = "giraffe-20",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -20,
                            EnclosureId = -6,
                            Name = "giraffe-21",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            EnclosureId = -6,
                            Name = "hippo-22",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -22,
                            EnclosureId = -6,
                            Name = "hippo-23",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -23,
                            EnclosureId = -6,
                            Name = "hippo-24",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -24,
                            EnclosureId = -6,
                            Name = "hippo-25",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -25,
                            EnclosureId = -6,
                            Name = "hippo-26",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -26,
                            EnclosureId = -6,
                            Name = "hippo-27",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -27,
                            EnclosureId = -6,
                            Name = "hippo-28",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -28,
                            EnclosureId = -6,
                            Name = "hippo-29",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -29,
                            EnclosureId = -6,
                            Name = "hippo-30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -30,
                            EnclosureId = -6,
                            Name = "hippo-31",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            EnclosureId = -6,
                            Name = "eagle-32",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -32,
                            EnclosureId = -6,
                            Name = "eagle-33",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -33,
                            EnclosureId = -6,
                            Name = "eagle-34",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -34,
                            EnclosureId = -6,
                            Name = "eagle-35",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -35,
                            EnclosureId = -6,
                            Name = "eagle-36",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -36,
                            EnclosureId = -6,
                            Name = "eagle-37",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -37,
                            EnclosureId = -6,
                            Name = "eagle-38",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -38,
                            EnclosureId = -6,
                            Name = "eagle-39",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -39,
                            EnclosureId = -6,
                            Name = "eagle-40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -40,
                            EnclosureId = -6,
                            Name = "eagle-41",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            EnclosureId = -6,
                            Name = "swan-42",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -42,
                            EnclosureId = -6,
                            Name = "swan-43",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -43,
                            EnclosureId = -6,
                            Name = "swan-44",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -44,
                            EnclosureId = -6,
                            Name = "swan-45",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -45,
                            EnclosureId = -6,
                            Name = "swan-46",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -46,
                            EnclosureId = -6,
                            Name = "swan-47",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -47,
                            EnclosureId = -6,
                            Name = "swan-48",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -48,
                            EnclosureId = -6,
                            Name = "swan-49",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -49,
                            EnclosureId = -6,
                            Name = "swan-50",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -50,
                            EnclosureId = -6,
                            Name = "swan-51",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            EnclosureId = -6,
                            Name = "python-52",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -52,
                            EnclosureId = -6,
                            Name = "python-53",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -53,
                            EnclosureId = -6,
                            Name = "python-54",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -54,
                            EnclosureId = -6,
                            Name = "python-55",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -55,
                            EnclosureId = -6,
                            Name = "python-56",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -56,
                            EnclosureId = -6,
                            Name = "python-57",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -57,
                            EnclosureId = -6,
                            Name = "python-58",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -58,
                            EnclosureId = -6,
                            Name = "python-59",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -59,
                            EnclosureId = -6,
                            Name = "python-60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -60,
                            EnclosureId = -6,
                            Name = "python-61",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            EnclosureId = -6,
                            Name = "tortoise-62",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -62,
                            EnclosureId = -6,
                            Name = "tortoise-63",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -63,
                            EnclosureId = -6,
                            Name = "tortoise-64",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -64,
                            EnclosureId = -6,
                            Name = "tortoise-65",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -65,
                            EnclosureId = -6,
                            Name = "tortoise-66",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -66,
                            EnclosureId = -6,
                            Name = "tortoise-67",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -67,
                            EnclosureId = -6,
                            Name = "tortoise-68",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -68,
                            EnclosureId = -6,
                            Name = "tortoise-69",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -69,
                            EnclosureId = -6,
                            Name = "tortoise-70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -70,
                            EnclosureId = -6,
                            Name = "tortoise-71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            EnclosureId = -6,
                            Name = "jellyfish-72",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -72,
                            EnclosureId = -6,
                            Name = "jellyfish-73",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -73,
                            EnclosureId = -6,
                            Name = "jellyfish-74",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -74,
                            EnclosureId = -6,
                            Name = "jellyfish-75",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -75,
                            EnclosureId = -6,
                            Name = "jellyfish-76",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -76,
                            EnclosureId = -6,
                            Name = "jellyfish-77",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -77,
                            EnclosureId = -6,
                            Name = "jellyfish-78",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -78,
                            EnclosureId = -6,
                            Name = "jellyfish-79",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -79,
                            EnclosureId = -6,
                            Name = "jellyfish-80",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -80,
                            EnclosureId = -6,
                            Name = "jellyfish-81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            EnclosureId = -6,
                            Name = "seahorse-82",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -82,
                            EnclosureId = -6,
                            Name = "seahorse-83",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -83,
                            EnclosureId = -6,
                            Name = "seahorse-84",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -84,
                            EnclosureId = -6,
                            Name = "seahorse-85",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -85,
                            EnclosureId = -6,
                            Name = "seahorse-86",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -86,
                            EnclosureId = -6,
                            Name = "seahorse-87",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -87,
                            EnclosureId = -6,
                            Name = "seahorse-88",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -88,
                            EnclosureId = -6,
                            Name = "seahorse-89",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -89,
                            EnclosureId = -6,
                            Name = "seahorse-90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -90,
                            EnclosureId = -6,
                            Name = "seahorse-91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            EnclosureId = -6,
                            Name = "octopus-92",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -92,
                            EnclosureId = -6,
                            Name = "octopus-93",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -93,
                            EnclosureId = -6,
                            Name = "octopus-94",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -94,
                            EnclosureId = -6,
                            Name = "octopus-95",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -95,
                            EnclosureId = -6,
                            Name = "octopus-96",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -96,
                            EnclosureId = -6,
                            Name = "octopus-97",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -97,
                            EnclosureId = -6,
                            Name = "octopus-98",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -98,
                            EnclosureId = -6,
                            Name = "octopus-99",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -99,
                            EnclosureId = -6,
                            Name = "octopus-100",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -100,
                            EnclosureId = -6,
                            Name = "octopus-101",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            EnclosureId = -6,
                            Name = "startfish-102",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -102,
                            EnclosureId = -6,
                            Name = "startfish-103",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -103,
                            EnclosureId = -6,
                            Name = "startfish-104",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -104,
                            EnclosureId = -6,
                            Name = "startfish-105",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -105,
                            EnclosureId = -6,
                            Name = "startfish-106",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -106,
                            EnclosureId = -6,
                            Name = "startfish-107",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -107,
                            EnclosureId = -6,
                            Name = "startfish-108",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -108,
                            EnclosureId = -6,
                            Name = "startfish-109",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -109,
                            EnclosureId = -6,
                            Name = "startfish-110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -110,
                            EnclosureId = -6,
                            Name = "startfish-111",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            EnclosureId = -6,
                            Name = "ladybug-112",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -112,
                            EnclosureId = -6,
                            Name = "ladybug-113",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -113,
                            EnclosureId = -6,
                            Name = "ladybug-114",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -114,
                            EnclosureId = -6,
                            Name = "ladybug-115",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -115,
                            EnclosureId = -6,
                            Name = "ladybug-116",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -116,
                            EnclosureId = -6,
                            Name = "ladybug-117",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -117,
                            EnclosureId = -6,
                            Name = "ladybug-118",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -118,
                            EnclosureId = -6,
                            Name = "ladybug-119",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -119,
                            EnclosureId = -6,
                            Name = "ladybug-120",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -120,
                            EnclosureId = -6,
                            Name = "ladybug-121",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -121,
                            EnclosureId = -6,
                            Name = "bumblebee-122",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -122,
                            EnclosureId = -6,
                            Name = "bumblebee-123",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -123,
                            EnclosureId = -6,
                            Name = "bumblebee-124",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -124,
                            EnclosureId = -6,
                            Name = "bumblebee-125",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -125,
                            EnclosureId = -6,
                            Name = "bumblebee-126",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -126,
                            EnclosureId = -6,
                            Name = "bumblebee-127",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -127,
                            EnclosureId = -6,
                            Name = "bumblebee-128",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -128,
                            EnclosureId = -6,
                            Name = "bumblebee-129",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -129,
                            EnclosureId = -6,
                            Name = "bumblebee-130",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -130,
                            EnclosureId = -6,
                            Name = "bumblebee-131",
                            Sex = 0,
                            SpeciesId = -13
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxNumOfAnimals")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -6,
                            MaxNumOfAnimals = 500,
                            Name = "First Enclosure"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 2,
                            Name = "eagle"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 2,
                            Name = "swan"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 1,
                            Name = "python"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 1,
                            Name = "tortoise"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 4,
                            Name = "jellyfish"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 4,
                            Name = "seahorse"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 5,
                            Name = "octopus"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 5,
                            Name = "startfish"
                        },
                        new
                        {
                            Id = -12,
                            Classification = 3,
                            Name = "ladybug"
                        },
                        new
                        {
                            Id = -13,
                            Classification = 3,
                            Name = "bumblebee"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosures")
                        .WithMany()
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosures");

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
